version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: me-android-studio_server_1
      APP_PORT: 3000

  server:
    image: tcbr10/android-studio:latest
    # user: "1000:1000"  <-- DELETE THIS LINE!
    init: false
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PUID: "1000"  # This tells the container to run apps as user 1000
      PGID: "1000"
      TZ: Asia/Jerusalem
    volumes:
      - ${APP_DATA_DIR}/data:/config
    devices:
      - /dev/kvm
      - /dev/dri
    privileged: true
    security_opt:
      - seccomp:unconfined
    shm_size: "2gb"
